"""
Pre-build script: overwrite MCCI LMIC's bundled project_config to select
the SX1262 radio and the correct region.  Runs before every compilation so
that `pio run --clean` doesn't reset the config.
"""
import os
from pathlib import Path

Import("env")

LMIC_CONFIG = """\
// Auto-generated by scripts/patch_lmic.py — do not edit by hand.
// Heltec WiFi LoRa 32 V3 uses SX1262.
#define CFG_sx1262_radio 1
#define LMIC_USE_INTERRUPTS
"""

def patch_lmic_config(source, target, env):
    libdeps_dir = Path(env.subst("$PROJECT_LIBDEPS_DIR")) / env["PIOENV"]
    lmic_dir = libdeps_dir / "MCCI LoRaWAN LMIC library" / "project_config"
    config_file = lmic_dir / "lmic_project_config.h"

    if not lmic_dir.exists():
        print("patch_lmic: MCCI LMIC not installed yet, skipping")
        return

    if config_file.read_text() != LMIC_CONFIG:
        config_file.write_text(LMIC_CONFIG)
        print(f"patch_lmic: patched {config_file}")


env.AddPreAction("compileasm", patch_lmic_config)
env.AddPreAction("compile", patch_lmic_config)
